development:
  adapter: postgresql
  database: feedme_development
  pool: 5

test:
  adapter: postgresql
  database: feedme_test
  pool: 5

production:
  adapter: postgresql
  database: feedme_production
  pool: 5  